
--regular
INSERT INTO buckets_of_ice_cream VALUES
(default, 'Vanilla'),
(default, 'Chocolate'),
(default, 'Strawberry'),
(default, 'Mint Chocolate Chip'),
(default, 'Cookies and Cream'),
(default, 'Rocky Road'),
(default, 'Butter Pecan'),
(default, 'Coffee'),
(default, 'Neapolitan'),
(default, 'Pistachio'),
(default, 'Cookie Dough'),
(default, 'Rainbow Sherbet'),
(default, 'Chocolate Chip'),
(default, 'Black Cherry'),
(default, 'Coconut'),
(default, 'Peanut Butter Cup'),
(default, 'Maple Walnut'),
(default, 'Caramel Swirl'),
(default, 'Banana Split'),
(default, 'Dogweed'),
(default, 'Red Velvet'),
(default, 'Lemon Sorbet'),
(default, 'Peppermint'),
(default, 'Mocha Almond Fudge'),
(default, 'Tiramisu'),
(default, 'Blueberry Cheesecake'),
(default, 'Raspberry Ripple'),
(default, 'Cinnamon'),
(default, 'Honey Lavender'),
(default, 'Green Tea Matcha'),
(default, 'Bubblegum'),
(default, 'Almond Joy');

--dairy free
INSERT INTO buckets_of_ice_cream VALUES
(default, 'Vanilla', TRUE),
(default, 'Chocolate', TRUE),
(default, 'Strawberry', TRUE),
(default, 'Mint Chocolate Chip', TRUE),
(default, 'Cookies and Cream', TRUE),
(default, 'Rocky Road', TRUE),
(default, 'Butter Pecan', TRUE),
(default, 'Coffee', TRUE),
(default, 'Neapolitan', TRUE),
(default, 'Pistachio', TRUE),
(default, 'Cookie Dough', TRUE),
(default, 'Rainbow Sherbet', TRUE),
(default, 'Chocolate Chip', TRUE),
(default, 'Black Cherry', TRUE),
(default, 'Coconut', TRUE),
(default, 'Peanut Butter Cup', TRUE),
(default, 'Maple Walnut', TRUE),
(default, 'Caramel Swirl', TRUE),
(default, 'Banana Split', TRUE),
(default, 'Dogweed', TRUE),
(default, 'Red Velvet', TRUE),
(default, 'Lemon Sorbet', TRUE),
(default, 'Peppermint', TRUE),
(default, 'Mocha Almond Fudge', TRUE),
(default, 'Tiramisu', TRUE),
(default, 'Blueberry Cheesecake', TRUE),
(default, 'Raspberry Ripple', TRUE),
(default, 'Cinnamon', TRUE),
(default, 'Honey Lavender', TRUE),
(default, 'Green Tea Matcha', TRUE),
(default, 'Bubblegum', TRUE),
(default, 'Almond Joy', TRUE);

--gluten free free
INSERT INTO buckets_of_ice_cream VALUES
(default, 'Vanilla', FALSE, TRUE),
(default, 'Chocolate', FALSE, TRUE),
(default, 'Strawberry', FALSE, TRUE),
(default, 'Mint Chocolate Chip', FALSE, TRUE),
(default, 'Cookies and Cream', FALSE, TRUE),
(default, 'Rocky Road', FALSE, TRUE),
(default, 'Butter Pecan', FALSE, TRUE),
(default, 'Coffee', FALSE, TRUE),
(default, 'Neapolitan', FALSE, TRUE),
(default, 'Pistachio', FALSE, TRUE),
(default, 'Cookie Dough', FALSE, TRUE),
(default, 'Rainbow Sherbet', FALSE, TRUE),
(default, 'Chocolate Chip', FALSE, TRUE),
(default, 'Black Cherry', FALSE, TRUE),
(default, 'Coconut', FALSE, TRUE),
(default, 'Peanut Butter Cup', FALSE, TRUE),
(default, 'Maple Walnut', FALSE, TRUE),
(default, 'Caramel Swirl', FALSE, TRUE),
(default, 'Banana Split', FALSE, TRUE),
(default, 'Dogweed', FALSE, TRUE),
(default, 'Red Velvet', FALSE, TRUE),
(default, 'Lemon Sorbet', FALSE, TRUE),
(default, 'Peppermint', FALSE, TRUE),
(default, 'Mocha Almond Fudge', FALSE, TRUE),
(default, 'Tiramisu', FALSE, TRUE),
(default, 'Blueberry Cheesecake', FALSE, TRUE),
(default, 'Raspberry Ripple', FALSE, TRUE),
(default, 'Cinnamon', FALSE, TRUE),
(default, 'Honey Lavender', FALSE, TRUE),
(default, 'Green Tea Matcha', FALSE, TRUE),
(default, 'Bubblegum', FALSE, TRUE),
(default, 'Almond Joy', FALSE, TRUE);